name: chatview_connect
description: "Specialized wrapper for chatview package providing seamless integration with Database & Storage for your flutter chat app."
version: 0.0.1
issue_tracker: https://github.com/SimformSolutionsPvtLtd/chatview_connect/issues
homepage: https://github.com/SimformSolutionsPvtLtd/chatview_connect
topics:
  - chatview
  - firebase
  - chat-backend
  - plug-and-play
  - backend-integration

platforms:
  android:
  ios:
  web:
  macos:
  windows:

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  # TODO(YASH): Use pub.dev version once chatview_utils latest version is released
  chatview_utils:
    git:
      url: https://github.com/SimformSolutionsPvtLtd/chatview_utils
      ref: feature/add_chatview_list_models

  cloud_firestore: ^6.0.0
  firebase_storage: ^13.0.1

  flutter:
    sdk: flutter

  http: ^1.4.0
  intl: ^0.20.2
  path: ^1.9.0
  rxdart: ^0.28.0
  uuid: ^4.5.1

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
